name: Build MOS

on:
  push:
    paths-ignore:
      - "lab-tutorial/**"
  workflow_dispatch:

jobs:
  build:
    name: "MOS Compilation Test"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt update
          sudo apt -y install nasm grub2-common mtools jq ninja-build qemu-system-x86 cpio libgmp-dev libmpfr-dev libmpc-dev

      - name: Download & Extract Cross Compiler
        run: |
          wget -q "https://github.com/moodyhunter/i686-elf-prebuilt/releases/download/artifact/toolchain-i686-elf.tar.gz"
          tar -xzf toolchain-i686-elf.tar.gz
          mv toolchain /tmp/
          echo "PATH=$PATH:/tmp/toolchain/bin" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -DMOS_DEBUG_ALL=ON \
            -DMOS_DEBUG_liballoc=OFF \
            -DBUILD_TESTING=ON \
            -B ${{github.workspace}}/build \
            -G Ninja

      - name: Build
        run: |
          cd ${{github.workspace}}/build
          ninja multiboot mos_userspace_programs mos_initrd
